from pptx import Presentation
from pptx.util import Inches, Pt
from PIL import Image, ImageDraw, ImageFont
import os
import textwrap

def create_pptx_file(slides_data, output_path):
    """
    Creates a PowerPoint file from the slide data.
    """
    prs = Presentation()

    for slide_data in slides_data:
        # Layout 1 is 'Title and Content'
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)

        # Title
        if slide.shapes.title:
            slide.shapes.title.text = slide_data.get("title", "Untitled Slide")

        # Content
        if len(slide.placeholders) > 1:
            content_placeholder = slide.placeholders[1]
            if content_placeholder.has_text_frame:
                tf = content_placeholder.text_frame
                content_list = slide_data.get("content", [])

                if content_list:
                    tf.text = content_list[0]
                    for point in content_list[1:]:
                        p = tf.add_paragraph()
                        p.text = point

        # Speaker Notes
        if slide.has_notes_slide:
            notes_slide = slide.notes_slide
            text_frame = notes_slide.notes_text_frame
            text_frame.text = slide_data.get("speaker_notes", "")

    prs.save(output_path)
    return output_path

def get_font(font_name, size):
    """
    Helper to load a font from the data/fonts directory.
    Falls back to default if not found.
    """
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    font_path = os.path.join(base_dir, "data", "fonts", font_name)

    try:
        if os.path.exists(font_path):
            return ImageFont.truetype(font_path, size)
    except Exception as e:
        print(f"Error loading font {font_name}: {e}")

    # Fallback to system search (Linux specific) or default
    try:
        return ImageFont.truetype("DejaVuSans.ttf", size)
    except:
        return ImageFont.load_default()

def create_slide_images(slides_data, output_dir):
    """
    Generates images for each slide using Pillow with improved layout.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    image_paths = []

    # Canvas Settings
    WIDTH = 1920
    HEIGHT = 1080
    BG_COLOR = (255, 255, 255)
    HEADER_COLOR = (44, 62, 80) # Dark Blue
    TEXT_COLOR = (50, 50, 50)
    TITLE_COLOR = (255, 255, 255)

    # Fonts
    title_font = get_font("DejaVuSans-Bold.ttf", 70)
    content_font = get_font("DejaVuSans.ttf", 45)
    footer_font = get_font("DejaVuSans.ttf", 30)

    # Margins
    MARGIN_X = 100
    MARGIN_Y_CONTENT = 300
    LINE_SPACING = 80

    for i, slide_data in enumerate(slides_data):
        img = Image.new('RGB', (WIDTH, HEIGHT), color=BG_COLOR)
        draw = ImageDraw.Draw(img)

        # 1. Header Bar
        header_height = 200
        draw.rectangle([(0, 0), (WIDTH, header_height)], fill=HEADER_COLOR)

        # 2. Title
        title = slide_data.get("title", "Untitled")
        # Center title vertically in header
        bbox = draw.textbbox((0, 0), title, font=title_font)
        title_w = bbox[2] - bbox[0]
        title_h = bbox[3] - bbox[1]
        title_x = MARGIN_X
        title_y = (header_height - title_h) / 2
        draw.text((title_x, title_y), title, font=title_font, fill=TITLE_COLOR)

        # 3. Content
        y_text = MARGIN_Y_CONTENT
        content_lines = slide_data.get("content", [])

        # Character wrapping approximation
        # 1920 width. Margin 100 on each side -> 1720 usable.
        # Font size 45. Approx 25px width per char? 1720 / 25 ~= 68 chars.
        # Let's be conservative with 60 chars.
        WRAP_WIDTH = 70

        for point in content_lines:
            wrapped_lines = textwrap.wrap(point, width=WRAP_WIDTH)
            for j, line in enumerate(wrapped_lines):
                bullet = "• " if j == 0 else "  "
                draw.text((MARGIN_X, y_text), f"{bullet}{line}", font=content_font, fill=TEXT_COLOR)
                y_text += LINE_SPACING

                # Prevent overflow
                if y_text > HEIGHT - 100:
                    break
            if y_text > HEIGHT - 100:
                break

        # 4. Footer
        footer_text = f"Slide {i+1} | Generated by AutoPresentation AI"
        bbox = draw.textbbox((0, 0), footer_text, font=footer_font)
        footer_w = bbox[2] - bbox[0]
        draw.text((WIDTH - footer_w - 50, HEIGHT - 50), footer_text, font=footer_font, fill=(150, 150, 150))

        image_filename = f"slide_{i+1:03d}.png"
        image_path = os.path.join(output_dir, image_filename)
        img.save(image_path)
        image_paths.append(image_path)

    return image_paths

def create_pdf_from_images(image_paths, output_path):
    """
    Compiles a list of images into a single PDF.
    """
    if not image_paths:
        return None

    images = [Image.open(p).convert('RGB') for p in image_paths]

    first_image = images[0]
    first_image.save(
        output_path,
        save_all=True,
        append_images=images[1:]
    )
    return output_path
